### ISSUE TITLE
使用Kmeans生成先验anchors报错， 运行python train.py报错

### ISSUE THREAD

**Issue by RAINzxy1007** [DataXujing/YOLO-V3-Tensorflow#24]
1.使用Kmeans生成先验anchors报错
(t1.9g) D:\Program Files\pycharm\code\Zhangxinyu_Safehat>python get_kmeans.py
Traceback (most recent call last):
  File "get_kmeans.py", line 143, in <module>
    anno_result = parse_anno(annotation_path, target_size=target_size)
  File "get_kmeans.py", line 101, in parse_anno
    img_w = int(float(s[2]))
ValueError: could not convert string to float: 'Files\\pycharm\\code\\Zhangxinyu_Safehat\\data/my_data/JPEGImages/000003.jpg'

2.运行 python train.py时报错

----------- start to train -----------

  0%|                                                                                                                     | 0/171 [00:00<?, ?it/s]2
021-04-13 18:10:27.341428: W C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\framework\op_kernel.cc:1306] Invalid argu
ment: ValueError: invalid literal for int() with base 10: 'Files\\pycharm\\code\\Zhangxinyu_Safehat\\data/my_data/JPEGImages/part2_000959.jpg'

**Comment by zhaoyong-li** [comment]
您好，请问这个问题解决了吗
